# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
from PyQt5.QtWidgets import QMainWindow
from PyQt5 import QtCore, QtGui, QtWidgets

class cl_Form_10(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 460)
        self.window = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(36, 52, 76);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 2, 500, 50))
        font = QtGui.QFont()
        font.setFamily("LCDMono2")
        font.setBold(True)
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 71, 81))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Thay.JPG"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 160, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 370, 71, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("phong.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 90, 250, 20))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 110, 100, 20))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(90, 130, 400, 20))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(90, 230, 100, 20))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(90, 210, 250, 20))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(90, 250, 400, 20))
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(90, 315, 100, 20))
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(90, 295, 250, 20))
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(90, 335, 400, 20))
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(90, 380, 250, 20))
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(90, 400, 300, 20))
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(90, 420, 400, 20))
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);\n")
        self.label_18.setObjectName("label_18")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 40, 190, 30))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setBold(True)
        self.label_1.setFont(font)
        self.label_1.setScaledContents(True)
        self.label_1.setObjectName("label_1")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 200, 71, 81))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("thy.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 285, 71, 81))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("do.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Infomation"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#4798a8;\">Visualize Data App</span></p></body></html>"))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#ff5500;\">LECTURERS</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Full name: Nguyen Dang Mai Thy"))
        self.label_7.setText(_translate("MainWindow", "Id: 20139039"))
        self.label_11.setText(_translate("MainWindow", "Major: Embedded Systems and Internet of Things"))
        self.label_12.setText(_translate("MainWindow", "Id: 20142623"))
        self.label_14.setText(_translate("MainWindow", "Full name: Tran Minh Do"))
        self.label_15.setText(_translate("MainWindow", "Major: Embedded Systems and Internet of Things"))
        self.label_17.setText(_translate("MainWindow", "Id: 20139036"))
        self.label_16.setText(_translate("MainWindow", "Full name: Nguyen Thanh Phong"))
        self.label_18.setText(_translate("MainWindow", "Major: Embedded Systems and Internet of Things"))
        self.label_3.setText(_translate("MainWindow", "Truong Quang Phuc, MEng"))
        self.label_5.setText(_translate("MainWindow", "Programming with Python Lab"))
        self.label_6.setText(_translate("MainWindow", "HoChiMinh City University of Technology and Education"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#ff5500;\">TEAM MEMBERS</span></p></body></html>"))


